### PR TITLE
Update to NAN 2 - fixed tests

### PR DESCRIPTION
**Pull request by bkw**
Son of #25. This is just to allow for easier merging. All Credits go to @kkoopa.

### CODE REVIEW

**Comment by bkw** [comment]
I tested this against pg-native and there see,s to be a problem with pg.cancel(). Will investigate.

**Comment by bkw** [comment]
I fixed cancel() to return the error in case struct allocation fails. This behaviour was inadvertently changed to throwing in the original patch.
Now the pg-native tests using this version of libpq pass.

**Comment by kkoopa** [comment]
Cool. Good that it got fixed.

**Comment by fundon** [comment]
👍🚀

**Comment by brianc** [comment]
@bkw thank you a bunch for fixing this!  I'll get this merged & a new version pushed up shortly.

**Pull request merged**
