### PR TITLE
Getting server version from connection object

### PR DESCRIPTION
**Pull request by Paxa**
I need to know server version to detect if some features are available (e.g. materialized views)

Usage:

```js
pq.serverVersion() //=> 90400
```

### CODE REVIEW

**Comment by brianc** [comment]
@Paxa this is amazing!!! Thank you!!  Merging & pushing out new minor version.

**Comment by brianc** [comment]
Published new version `libpq@1.8.0`

**Comment by Paxa** [comment]
Awesome. Thanks :+1:

**Comment by brianc** [comment]
Thank __YOU__ :dancer:

**Pull request merged**
